### ISSUE TITLE
web page inaccessable

### ISSUE THREAD

**Issue by Forec** [baidu/Curve#11]
After updating to the new commit `84acec7`, the web page could not be visited, which indicates: `{"message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."}`

![image](https://user-images.githubusercontent.com/13556999/32219174-4dac4f46-bdfb-11e7-9ce6-62bd71cb8d58.png)

**Comment by ldp12416** [comment]
Fixed. Thank you.
