### ISSUE TITLE
export the data file 

### ISSUE THREAD

**Issue by znw0714** [baidu/Curve#13]
I use the sample_data_10000.csv file and export the labeled  file. 
[sample_data_10000.csv.zip](https://github.com/baidu/Curve/files/1436139/sample_data_10000.csv.zip)
 

- The columns names are missing.
- The timestamp are wrong.
[sample_data_10000_labeled.csv.zip](https://github.com/baidu/Curve/files/1436146/sample_data_10000_labeled.csv.zip)
@ldp12416

**Comment by minorcong** [comment]
We used to export in selected format —— no header and human readable timestamp. This has changed in 9 Nov. It will be exported in the same format as adding.
