### ISSUE TITLE
display problem 

### ISSUE THREAD

**Issue by znw0714** [baidu/Curve#14]
![screen shot 2017-11-02 at 9 19 43 am](https://user-images.githubusercontent.com/17549367/32305262-761560b0-bf42-11e7-9321-a95eb106d262.png)

**Comment by cuiy245** [comment]
Hello, the latest version has been fixed, please update the code, if there are problems, I will continue to follow up, thank you

**Comment by minorcong** [comment]
![image](https://user-images.githubusercontent.com/4161574/34432330-3c1d7fb8-ecb1-11e7-84cc-9f5021b25a3d.png)

@cuiy245 Unfortunately, this problem has not been completely repaired.

**Comment by cuiy245** [comment]
Hello, the problem has been fixed, thank you
