### ISSUE TITLE
about the button of time range

### ISSUE THREAD

**Issue by znw0714** [baidu/Curve#15]
![screen shot 2017-11-02 at 12 21 53 pm](https://user-images.githubusercontent.com/17549367/32309719-967cd36a-bf5b-11e7-9272-8d7eedc70b6c.png)
As the figure shows, I choose the time range is 3d, while the buttons of 7d and 14d do not work. That is to say, the time range can only be narrowed, not expanded. The only way to show the larger time range is reloading the data. Besides, it would be better if the selected time range button is highlighted.
@ldp12416

**Comment by cuiy245** [comment]
Hello, the latest version has been fixed, please update the code, if there are problems, I will continue to follow up, thank you
