### ISSUE TITLE
Bugs found during trial

### ISSUE THREAD

**Issue by Forec** [baidu/Curve#2]
* Data more than I have selected is labelled as anomaly
* Buttons `cancel the label`, `export`, `delete` and some non-texted interactive functions are inactive
* Value of `anomaly percent` does not change according to the labelled curves
* Some of the curves I have labelled lost after refreshing
@ldp12416 Enjoy

**Comment by Forec** [comment]
Maybe `labelling` not `labeling` ? @ldp12416 Enjoy

**Comment by znw0714** [comment]
- some .csv data files upload failed. What are the specific requirements for uploading files? for example column names, etc.

**Comment by ldp12416** [comment]
@Forec please split the four bugs into four issues, so we can track them individually. Thanks.

**Comment by Forec** [comment]
Sure.
