### ISSUE TITLE
Some data files upload failed

### ISSUE THREAD

**Issue by znw0714** [baidu/Curve#3]
Some .csv data file upload failed. What are the specific requirements for uploading files? such as column names, etc.

**Comment by ldp12416** [comment]
Thank @znw0714  for the feedback. We will add a description about the data format in README.

Please attach the data file which is failed to upload. We will see if we can support that format. (If the file is too large or is confidential, a sample of the file will work too.)

**Comment by znw0714** [comment]
The github issue can not upload .csv file. This is the local screenshots about the file. Probably because missing timestamp? label is null?  @ldp12416 

![image](https://user-images.githubusercontent.com/17549367/32156154-9b999c7e-bd09-11e7-979f-11ee90e42d58.png)

**Comment by znw0714** [comment]
I find that some .csv files are reported uploaded failed by Curve. But after a period of time, it magically appears in the data list.

**Comment by ldp12416** [comment]
I just updated data format in README, please  see what formats are supported now. @znw0714
