### ISSUE TITLE
the latest version can't compile

### ISSUE THREAD

**Issue by sure0000** [baidu/Curve#37]
## when i compile the latest version ,i found an error
 > "Module not found: Error: Can't resolve 'react-icons/lib/fa/search' in '/anaconda3/envs/python3/Curve/web/src/index/component'" 

## my python version is Python 3.6.4 :: Anaconda, Inc, i don't konw what happen and can't find the log file. please help me.

**Comment by minorcong** [comment]
I'm sorry for that bug, and it was fixed in https://github.com/baidu/Curve/commit/2cdf33d8667e4693d311ae7ac7b491b12d261ee8

**Comment by minorcong** [comment]
btw, the versions in release list is recommend: https://github.com/baidu/Curve/releases

**Comment by minorcong** [comment]
@sure0000 We use virtual env to separate curve env with your local env in build.sh, and the conflict between conda and virtual env is still unsettled.
I tried to use ```python --version``` to identify Anaconda during build, but it doesn't work sometimes, would you like to solve this problem?

**Comment by sure0000** [comment]
i'am working on my paper those days, maybe later i will try to fix it.

**Comment by minorcong** [comment]
Thx for sure0000, The conflict between conda and venv has been recorded in https://github.com/baidu/Curve/issues/5 .
As the error during web build is fixed, issue#37 close.
