### ISSUE TITLE
about time interval and time range

### ISSUE THREAD

**Issue by znw0714** [baidu/Curve#4]
I try to upload a file and the original time interval is 1min, while the interval in Curve is 1s and the start time is 1970 ?
![image](https://user-images.githubusercontent.com/17549367/32155778-77181ee0-bd07-11e7-85b2-93f9c86a772b.png)

**Comment by ldp12416** [comment]
Could you give some timestamps in the data?  or a sample file?

**Comment by znw0714** [comment]
![image](https://user-images.githubusercontent.com/17549367/32156179-c9049ea2-bd09-11e7-817f-456211aa4bb8.png)
@ldp12416

**Comment by ldp12416** [comment]
Thanks. @minorcong please take over this issue.

**Comment by ldp12416** [comment]
[sample_data_10000.csv.zip](https://github.com/baidu/Curve/files/1426170/sample_data_10000.csv.zip)

@znw0714 please try the data file attached (unzip before loading). The timestamp format looks like the same as yours, but it works well here.

btw, you can zip a sample file and then attach it in the comment.

**Comment by znw0714** [comment]
[sample1.zip](https://github.com/baidu/Curve/files/1430897/sample1.zip)
Yes, I tried your sample file successfully. This is my sample file that doesn't work.
![image](https://user-images.githubusercontent.com/17549367/32227059-2e24a76e-be18-11e7-8dab-2fbe29b71bcd.png)

**Comment by ldp12416** [comment]
Please see README for the data formats are supported now. Thanks!
