### ISSUE TITLE
can't load CSV file 

### ISSUE THREAD

**Issue by ray1888** [baidu/Curve#42]
i want to try your system with a labeled csv file , but it just show can't "Curve upload failed ,Please try again ", so what is the problem ?  and  i want to modify your system with more Input Source(like TimeSeriesDatabase , are you guys welcome on this? if we are done , we will give the PR to you ) , hope that you can reply why the problem show and how to fix it .

**Comment by ray1888** [comment]
my data is like this ( show in a jupyter notebook)
```
output2.head(10)
## output2 is a pandas dataframe to show in jupyter notebook , but the format is the same with the given csv file 
```

out:
	timestamp	value
0	1493568000	1.901639
1	1493568060	1.786885
2	1493568120	2.000000
3	1493568180	1.885246
4	1493568240	1.819672
5	1493568300	1.885246
6	1493568360	1.885246
7	1493568420	1.934426
8	1493568480	1.967213
9	1493568540	1.950820

**Comment by ray1888** [comment]
the first column is Index,in the csv file , they didn't exist

**Comment by ray1888** [comment]
需要我提供我用于测试的csv文件给你们吗？因为我直接用你们的演示网站那里也是上传失败的

**Comment by minorcong** [comment]
Any detail? eg. http://curve.baidu.com or private build? what's the filename?
![image](https://user-images.githubusercontent.com/4161574/38476442-59e9be7a-3be0-11e8-840e-0c1a1d5c07b4.png)

**Comment by ray1888** [comment]
我发你github的联系邮箱吧

**Comment by minorcong** [comment]
好的

**Comment by minorcong** [comment]
An ENCODING Bug is fixed. https://github.com/baidu/Curve/commit/ba064999bd7e1cf9dd32313e0924a6e9bb202ba3

**Comment by cqzhlei** [comment]
请问下，上传csv文件，时间戳列能不能重复？？
