### ISSUE TITLE
Incompatible between conda and virtualenv

### ISSUE THREAD

**Issue by znw0714** [baidu/Curve#5]
I find that if your computer installed Anoconda, the build process will report errors.  The solution is delete the Anoconda folder, when the environment build is finished, then restore the Anoconda folder.

**Comment by ldp12416** [comment]
Thanks, we will check this out.

**Comment by minorcong** [comment]
I checked the problem and found the incompatible between conda and virtualenv.  ╮(╯_╰)╭

**Comment by ldp12416** [comment]
This could be a problem. We can fix it, but maybe later. First focus on those critical bugs.

 @znw0714 thanks for the feedback. If you have any further suggestion to solve this problem, please feel free to add a comment.  I will keep this issue open.

**Comment by minorcong** [comment]
Add a control in https://github.com/baidu/Curve/commit/6d6fbbab73bd3dbadd185cdfc63a317525492dd7 for conda
