### ISSUE TITLE
Incorrect time series naming from first dotted element of the uploaded csv file

### ISSUE THREAD

**Issue by earthgecko** [baidu/Curve#53]
Curve seems to be naming the time series incorrectly, based on the first dotted element in the csv filename.
I uploaded a csv named ```stats.statsd.bad_lines_seen.20161110.ts.value.csv``` and the Curve web app presented it as ```stats```.
I tested this further by uploading a file named ```stats.graphite-dev-2.vda.ioInProgress.baidu_curve.csv``` and was presented with the error:

> stats upload failed...Can't upload file with the same name, please try again

I then renamed the file to ```stats-graphite-dev-2.vda.ioInProgress.baidu_curve.csv``` which did upload to Curve, but named the time series ```stats-graphite-dev-2```

It would probably be better if Curve just named the time series based on the filename, excluding the ```.csv``` extension.

**Comment by cuiy245** [comment]
Hello, the problem has been received, is being followed up, the latest results will be updated here in time, thank you

**Comment by cuiy245** [comment]
Hello, the problem has been fixed, thank you for your feedback

**Comment by earthgecko** [comment]
Thanks @cuiy245 I can confirm that https://github.com/baidu/Curve/commit/9ed828e33fd1f60cbc57abffc9f7b5ab91e603d8 has fixed the problem, it also required a Crtl+F5 in the browser too :)
