### ISSUE TITLE
[Solution] Left preview delete button does not work

### ISSUE THREAD

**Issue by zishuow** [baidu/Curve#66]
Clicking triple dots at the right side of the specific data in left side-bar, then clicking 'delete'. In the pop-up window, the red 'delete' button does not work.

Raise error : 
` Uncaught TypeError: this.props.showLoading is not a function
    at e.value (dialog.js:58)
    at Object.i (ReactErrorUtils.js:24)
    at a (EventPluginUtils.js:83)
    at Object.s [as executeDispatchesInOrder] (EventPluginUtils.js:106)
    at p (EventPluginHub.js:41)
    at m (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)
    at i (forEachAccumulated.js:22)
    at Object.processEventQueue (EventPluginHub.js:252)
    at i (ReactEventEmitterMixin.js:15)`

**Comment by zishuow** [comment]
I have found a solution for this
if anyone is interested, here is how:

file:    /Curve-master/web/src/index/component/index.js 
Line 149 
```showLoading={this.showLoading}```
add in the following line
```hideLoading={this.hideLoading}```

Line 190
 change to 
``` <Dialog showLoading={this.showLoading}  hideLoading={this.hideLoading} ref="dialog"></Dialog>```

file:   /Curve-master/web/src/index/component/sidebar.js

Line 151 - 153 
change to 
```             
let nextDataName = null;
let nextUrl = '';
if (index< list.length-1){
      nextDataName = list[index + 1].name;
}
if (nextDataName) {
      nextUrl = '/home/' + nextDataName;
}   
```
Problem sloved~

**Comment by mistycheney** [comment]
Even with the above changes, I still have this problem~~

**Comment by mistycheney** [comment]
Thanks for this fix. It works. Just note that these changes must be done before `./control.sh start`.
