### ISSUE TITLE
[Solution] TypeError: generate() got an unexpected keyword argument 'swagger'

### ISSUE THREAD

**Issue by FudanYuan** [baidu/Curve#68]
When run the command "./control.sh start" to start the service, there exists the error message in the console. I want to know how to fix it or what environment should I install, thanks. Current environment is Mac OS 10.14.2, python 3.6.3, Node.js 6.4.1.

**Comment by mistycheney** [comment]
I also encounter this problem on Ubuntu 16.04 with Node.js v11.11.0

**Comment by wang23795** [comment]
I have encountered this problem on centos7 with node.js6

**Comment by wang23795** [comment]
I solved this problem by：pip uninstall click && pip install click==6.7

**Comment by mistycheney** [comment]
Thanks! That solves the problem.

**Comment by lithces** [comment]
similar issue, solved by manually install click==6.7 in venv.
