### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by navneeth** [baidu/Curve#69]
Hi - I have got the app running. But uploading a csv fails with the error
Error: Request failed with status code 500

The page shows "Uploading and pre-processing, please wait.."

**Comment by navneeth** [comment]
Any hints on debuging the issue would be appreciated.

**Comment by minorcong** [comment]
More information is needed to reproduce the problem, such as the uploaded data file, the log file api/log/uwsgi.log

**Comment by navneeth** [comment]
Please ignore this & see #72 instead. I will add details of the log file etc in that issue.
