### ISSUE TITLE
Interactive Labeling

### ISSUE THREAD

**Issue by Dahlia7** [baidu/Curve#74]
Hey guys,

May I ask whether it's possible to label on single point as an outlier? I've tried many ways like selecting relatively narrow range on the time series but it looks like minimum 2 points are labeled every time.

Was I doing something incorrectly?

Thanks for helping in advance.

<img width="553" alt="tmp" src="https://user-images.githubusercontent.com/8780698/69841018-93aae180-1298-11ea-8c88-1dd43f57d905.png">

**Comment by minorcong** [comment]
There is a lack of display, single abnormal points are not displayed now, although the label has been saved.

**Comment by Dahlia7** [comment]
> There is a lack of display, single abnormal points are not displayed now, although the label has been saved.

Thanks and tested!
