### ISSUE TITLE
Some of the curves I have labelled lost after refreshing the web page

### ISSUE THREAD

**Issue by Forec** [baidu/Curve#8]
`lost` means these curves are not labelled anomaly after refreshing.

**Comment by minorcong** [comment]
Would you like to add more description about you operation? Like "labelled without other operation" or "labelled a large field then cancel a small field but all label lost"

**Comment by Forec** [comment]
Sure. This phenomenon has only appeared once, and I have never met again. I labelled a continuous long curve, without any other operation, and clicked the refresh button of the browser immediately, then the data I just labelled was rendered in blue but not red.

**Comment by ldp12416** [comment]
How long of the data did you label? One month or longer? Maybe it takes more time to store a longer  label. I tried label 2 months of data and it is ok. We will try to test more cases.

Close this issue for now. If this bug happen again, please give some details so we can reproduce it.
