### ISSUE TITLE
Value of anomaly percent does not change according to the labelled curves

### ISSUE THREAD

**Issue by Forec** [baidu/Curve#9]
![image](https://user-images.githubusercontent.com/13556999/32158200-8913235c-bd15-11e7-976a-9c15ccf559e6.png)
The `Anomaly percent` does not change.

**Comment by cuiy245** [comment]
Hello, I have repaired, please verify

**Comment by Forec** [comment]
Thanks. Please take a look at the new [issue](https://github.com/baidu/Curve/issues/11), the latest code makes web interface inaccessable.

**Comment by cuiy245** [comment]
Hello, this problem is being repaired, thank you
